spring.application.name=document-management-backend
spring.datasource.url=jdbc:postgresql://ep-divine-pond-a12ycmj9.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_auoUFmB5ep2b
spring.datasource.driver-class-name=org.postgresql.Driver

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Max size cho m?i file
spring.servlet.multipart.max-file-size=10MB

# Max size cho to�n b? request (nhi?u file)
spring.servlet.multipart.max-request-size=20MB

application.service.impl.secret-key=YOsfnd1S04sD4Gcb3AH0F2EWqjj4koBV304bM3dj1BF
application.service.impl.expiration=6000000
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true